annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 3.0.1
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
  - condition: cassandra.enabled
    name: cassandra
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
description: Kong is an open source Microservice API gateway and platform designed for managing microservices requests of high-availability, fault-tolerance, and distributed systems.
engine: gotpl
home: https://github.com/bitnami/charts/tree/main/bitnami/kong
icon: https://bitnami.com/assets/stacks/kong/img/kong-stack-220x234.png
keywords:
  - kong
  - ingress
  - openresty
  - controller
  - http
  - web
  - www
  - reverse proxy
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: kong
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/kong
  - https://konghq.com/
version: 8.0.22
